### ISSUE TITLE
OutOfMemoryError when initializing Noodle after several usage

### ISSUE THREAD

**Issue by jpaulo1205** [nolia/Noodle#1]
```
 java.lang.OutOfMemoryError: Failed to allocate a 808674370 byte allocation with 6077136 free bytes and 183MB until OOM
                                                                             at com.noodle.storage.FileMappedBufferStorage.remapIndexes(FileMappedBufferStorage.java:60)
                                                                             at com.noodle.storage.FileMappedBufferStorage.<init>(FileMappedBufferStorage.java:43)
                                                                             at com.noodle.Noodle$Builder.build(Noodle.java:275)
```

using the Noodle builder like this on Activity, onCreate:
```
this.noodle = Noodle
                .with(this)
                .addType(Description
                        .of(Model.class)
                        .withGetIdOperator(new Description.GetIdOperator<Model>() {
                            @Override
                            public long getId(Model model) {
                                return model.id;
                            }
                        })
                        .withSetIdOperator(new Description.SetIdOperator<Model>() {
                            @Override
                            public void setId(Model model, long id) {
                                model.id = id;
                            }
                        })
                        .build()
                )
                .build();
```

**Comment by nolia** [comment]
Hello @jpaulo1205 !
Are you using v0.5 or snapshot? Could you please describe a bit more in detail your Model class and its usages? Like what operations are being performed before it crashes?

**Comment by nolia** [comment]
@jpaulo1205 this should be fixed in latest `master-SNAPSHOT` build. Please, see #4 on more details.
