### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by andreag85** [nolia/Noodle#4]
I'm got the following error
> E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: it.nullpointer.pizza, PID: 16767
                                                                      java.lang.OutOfMemoryError: Failed to allocate a 1768841606 byte allocation with 5764948 free bytes and 91MB until OOM
                                                                          at com.noodle.storage.ByteBufferStorage.getRecordAt(ByteBufferStorage.java:197)
                                                                          at com.noodle.storage.ByteBufferStorage.get(ByteBufferStorage.java:173)
                                                                          at com.noodle.collection.StoredConvertedCollection.findItemsWith(StoredConvertedCollection.java:123)
                                                                          at com.noodle.collection.StoredConvertedCollection.access$300(StoredConvertedCollection.java:17)
                                                                          at com.noodle.collection.StoredConvertedCollection$5.call(StoredConvertedCollection.java:104)
                                                                          at com.noodle.collection.StoredConvertedCollection$5.call(StoredConvertedCollection.java:101)
                                                                          at com.noodle.Result.now(Result.java:36)
                                                                          at it.nullpointer.pizza.manager.PizzeManager.getPizze(PizzeManager.java:31)
                                                                          at it.nullpointer.pizza.utils.Utils.tipiDiPizze(Utils.java:49)
                                                                          at it.nullpointer.pizza.ui.fragment.CreaOrdineFragment.onCreate(CreaOrdineFragment.java:65)
                                                                          at android.support.v4.app.Fragment.performCreate(Fragment.java:2177)
                                                                          at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1244)
                                                                          at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1080)
                                                                          at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:971)
                                                                          at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:95)
                                                                          at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2143)
                                                                          at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2098)
                                                                          at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2008)
                                                                          at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:135)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5258)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

executing `noodle.collectionOf(TipoDiPizza.class).all().now();`

Now every time I open the app have a crash

> E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: it.nullpointer.pizza, PID: 21756
                                                   java.lang.OutOfMemoryError: Failed to allocate a 1734895916 byte allocation with 4018592 free bytes and 94MB until OOM
                                                       at com.noodle.storage.FileMappedBufferStorage.remapIndexes(FileMappedBufferStorage.java:60)
                                                       at com.noodle.storage.FileMappedBufferStorage.<init>(FileMappedBufferStorage.java:43)
                                                       at com.noodle.storage.FileMappedBufferStorage.<init>(FileMappedBufferStorage.java:20)
                                                       at com.noodle.Noodle.<init>(Noodle.java:66)
                                                       at it.nullpointer.pizza.manager.OrdiniManager.<init>(OrdiniManager.java:24)
                                                       at it.nullpointer.pizza.PizzaApp.onCreate(PizzaApp.java:21)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4557)
                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:151)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5258)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

creating noodle instance with
`noodle = new Noodle(context)
                .registerType(OrdineDinamico.class, Description.of(OrdineDinamico.class).withIdField("noodleId").build())
                .registerType(OrdineDiUnTipo.class, Description.of(OrdineDiUnTipo.class).withIdField("noodleId").build());`

I tried with both v0.5 and snapshot.

I have 2 different manager with each different model (2 model the first and 1 the second), is this a problem?

Attached you can find the noodle file, the only one I found in the device, hoping can help.

[data.noodle.zip](https://github.com/nolia/Noodle/files/842438/data.noodle.zip)

**Comment by nolia** [comment]
Hello @andreag85 ! Thanks a lot for such a detailed info. 
Having 2 different managers to access the data should not give any problems, unless you are using 2 different Noodle instances. This may cause file mapped buffer to be unsynced - and so the file to be corrupted.  
Regarding the crash - yes, it's a known issues and I've been working on it recently. Thanks a lot for the file, this may help me a lot.  
My understanding of this now is when application crashes (for any reason) - the memory buffer does not get into the file correctly. This causes Noodle to crash on start.  
Maybe you have steps to reproduce the first crash, which causes discrepancy in the first place, I would appreciate it.

**Comment by andreag85** [comment]
Hello,
have you received my mail?
The update is that using only one manager seems no more crash occurs.

**Comment by nolia** [comment]
@andreag85 hey! Thank you for help.  
I've rewrote the storage class to use synchronized random access file instead of mapped file buffer.   
Please, update to latest `master-SNAPSHOT`.
