### ISSUE TITLE
Out of Memory Exception

### ISSUE THREAD

**Issue by ikymasie** [nolia/Noodle#5]
Hi im having an issue using the library... i can successfully save to a collection... a retrieve it.. but when i save more info to the collection and try and retrieve it.. i get the following logcat error `java.lang.OutOfMemoryError: Failed to allocate a 1869443181 byte allocation with 4290660 free bytes and 249MB until OOM
                                                                                  at com.noodle.storage.FileMappedBufferStorage.remapIndexes(FileMappedBufferStorage.java:60)
                                                                                  at com.noodle.storage.FileMappedBufferStorage.<init>(FileMappedBufferStorage.java:43)
                                                                                  at com.noodle.Noodle$Builder.build(Noodle.java:276)`

Any Ideas?

**Comment by nolia** [comment]
Hi @ikymasie 

Judging from the stacktrace, you are probably using version 0.5 of Noodle with `FileMappedBufferStorage`, which was buggy and not properly works with concurrent operations and re-opening same file. Please be sure to update to `master-SNAPSHOT` version - this issue is fixed there.

Also, one more hint: be sure to use *only one* instance of `Noodle` object in your application - the synchronization is managed by the storage and there may be discrepancies if you open same file from more than one place in your code. So just make it a singleton.

Thanks!
