### ISSUE TITLE
android 7.0 crash on delete

### ISSUE THREAD

**Issue by Dkhusainov** [nolia/Noodle#7]
I use latest noodle from this 
'compile 'com.github.nolia:Noodle:5a59e9940175120b973f879a389a54d2df2706c7''

Here's the sample

class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        val n = Noodle.with(this).build()
        n.put("test1", Test("test1")).now()
        n.put("test2", Test("test2")).now()
        n.put("test3", Test("test3")).now()
        n.delete("test2").now()
    }

    class Test(val str: String)
}

Throws the following exception. Happens only on android 7.0(both emulator and real device).

`Caused by: java.lang.RuntimeException: java.lang.NullPointerException: src == null
                                                                                  at com.noodle.Result.now(Result.java:38)
                                                                                  at com.example.khusainovd.luatest.MainActivity.onCreate(MainActivity.kt:16)
                                                                                  at android.app.Activity.performCreate(Activity.java:6679)
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                                                  at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                  at android.os.Looper.loop(Looper.java:154) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
                                                                               Caused by: java.lang.NullPointerException: src == null
                                                                                  at java.lang.System.arraycopy(System.java:504)
                                                                                  at java.nio.DirectByteBuffer.compact(DirectByteBuffer.java:282)
                                                                                  at com.noodle.storage.RandomAccessFileStorage.remove(RandomAccessFileStorage.java:95)
                                                                                  at com.noodle.Noodle$3.call(Noodle.java:177)
                                                                                  at com.noodle.Noodle$3.call(Noodle.java:174)
                                                                                  at com.noodle.Result.now(Result.java:36)
                                                                                  at com.example.khusainovd.luatest.MainActivity.onCreate(MainActivity.kt:16) 
                                                                                  at android.app.Activity.performCreate(Activity.java:6679) 
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618) 
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                                                  at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                  at android.os.Looper.loop(Looper.java:154) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) `

**Comment by nolia** [comment]
Apparently, file memory mapping does not work as expected on ≥ 7.0 versions. Switched to bytes copying approach in latest commit on master. Should have fixed it.

**Comment by Dkhusainov** [comment]
Thanks, it works now. You can close the issue.
